"""Hard limits and shared defaults. Single source of truth for validation."""

from __future__ import annotations

MAX_NAME_CHARS = 80
MAX_POINT_CHARS = 120
MAX_POINTS = 12
MIN_POINTS = 1
MAX_AUDIENCE_CHARS = 80
MAX_CATEGORY_CHARS = 40
MAX_PRICE_CHARS = 30
MAX_BRAND_CHARS = 40
MAX_DESCRIPTION_CHARS = 2000
MAX_TOTAL_INPUT_CHARS = 8000
MIN_DURATION_SEC = 8
MAX_DURATION_SEC = 180
DEFAULT_LANGUAGE = "zh"
SUPPORTED_LANGUAGES = ("zh", "en")
STYLE_COUNT = 3
MIN_SHOTS = 3
HOOK_TARGET_SEC = 3.0
VERSION = "0.1.0"
